version: '2.1'
services:

  project:
    build:
      context: ./
    env_file: .env
    working_dir: /djangodocker
    restart: "always"
    depends_on:
     - postgresql
    command: bash -c "sleep 3 && /etc/init.d/ssh start && python3 /djangodocker/manage.py runserver 0.0.0.0:8000"
    # supervisord -c /djangodocker/supervisord.conf -n"
    volumes:
      - /work/djangodocker:/djangodocker
      - ./dockerfiles/sshdconf/sshd_config:/etc/ssh/sshd_config
      - ./dockerfiles/id_rsa.pub:/root/.ssh/authorized_keys
      - /home/alex/.PyCharm2018.1/:/root/.pycharm_helpers/
      - ./dockerfiles/logs/supervisord.conf:/djangodocker/logs/supervisord.conf
      - ./djangod.conf:/djangodocker/djangod.conf
    links:
      - postgresql
    ports:
      - "2225:22"
      - "8005:8000"

  postgresql:
    image: postgres:9.6-alpine
    env_file: .env
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"

